[package]
name = "interp-toy"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = {git = "https://github.com/xi-editor/druid", rev = "88d18be0155791cac0d910f22d0552dd44ec3814" }
rbf-interp = "0.1.3"
nalgebra = "0.18"
